module ExplanationsHelper
  def calculate_local_values_for_variance(prop)
    if prop.variance_threshold == nil
      variance_percentage = !(prop.portfolio.portfolio_type.variance_percentage.nil? ||  prop.portfolio.portfolio_type.variance_percentage.blank? ||  prop.portfolio.portfolio_type.variance_percentage == "") ? prop.portfolio.portfolio_type.variance_percentage : "0"
      variance_percentage_ytd = !(prop.portfolio.portfolio_type.variance_percentage_ytd.nil? ||  prop.portfolio.portfolio_type.variance_percentage_ytd.blank? ||  prop.portfolio.portfolio_type.variance_percentage_ytd == "") ? prop.portfolio.portfolio_type.variance_percentage_ytd : "0"
      variance_and,variance_or = !(prop.portfolio.portfolio_type.and_or.nil? ||  prop.portfolio.portfolio_type.and_or.blank? ||  prop.portfolio.portfolio_type.and_or == "") ? [prop.portfolio.portfolio_type.and_or == "and" ? "checked" : "",prop.portfolio.portfolio_type.and_or == "or" ? "checked" : ""] : ["",""]
      variance_and_ytd,variance_or_ytd = !(prop.portfolio.portfolio_type.and_or_ytd.nil? ||  prop.portfolio.portfolio_type.and_or_ytd.blank? ||  prop.portfolio.portfolio_type.and_or_ytd == "") ? [prop.portfolio.portfolio_type.and_or_ytd == "and" ? "checked" : "" ,prop.portfolio.portfolio_type.and_or_ytd == "or" ? "checked" : "" ] : ["",""]
      variance_amount = !(prop.portfolio.portfolio_type.variance_amount.nil? ||  prop.portfolio.portfolio_type.variance_amount.blank? || prop.portfolio.portfolio_type.variance_amount == "") ? prop.portfolio.portfolio_type.variance_amount : "0"
      variance_amount_ytd = !(prop.portfolio.portfolio_type.variance_amount_ytd.nil? || prop.portfolio.portfolio_type.variance_amount_ytd.blank? || prop.portfolio.portfolio_type.variance_amount_ytd == "") ? prop.portfolio.portfolio_type.variance_amount_ytd : "0"
      cap_exp_variance_amt = !(prop.portfolio.portfolio_type.cap_exp_variance.nil? || prop.portfolio.portfolio_type.cap_exp_variance.blank? || prop.portfolio.portfolio_type.cap_exp_variance == "") ? prop.portfolio.portfolio_type.cap_exp_variance : "0"
      cap_exp_variance_amt_ytd = !(prop.portfolio.portfolio_type.cap_exp_variance_ytd.nil? ||  prop.portfolio.portfolio_type.cap_exp_variance_ytd.blank? || prop.portfolio.portfolio_type.cap_exp_variance_ytd == "") ? prop.portfolio.portfolio_type.cap_exp_variance_ytd : "0"
    else
      variance_percentage = prop.variance_threshold.variance_percentage
      variance_and = prop.variance_threshold.and_or == "and" ? "checked" : ""
      variance_or = prop.variance_threshold.and_or == "or" ? "checked" : ""
      variance_amount = prop.variance_threshold.variance_amount
      cap_exp_variance_amt = prop.variance_threshold.cap_exp_variance
      variance_percentage_ytd = prop.variance_threshold.variance_percentage_ytd
      variance_and_ytd = prop.variance_threshold.and_or_ytd == "and" ? "checked" : ""
      variance_or_ytd = prop.variance_threshold.and_or_ytd == "or" ? "checked" : ""
    variance_amount_ytd = prop.variance_threshold.variance_amount_ytd
    cap_exp_variance_amt_ytd = prop.variance_threshold.cap_exp_variance_ytd
    end
    return variance_percentage,variance_and,variance_or,variance_amount,cap_exp_variance_amt,variance_percentage_ytd,variance_and_ytd,variance_or_ytd,variance_amount_ytd,cap_exp_variance_amt_ytd
  end

  def generate_explanation(page,table_name)

    if @partial == "variances"
      if @condition == "true"
        page << "jQuery('#{table_name}').html('<div class=add-explanation><div class=tablecoll5 style=margin-left:413px;width:181px;overflow:hidden;line-height:16px;><textarea id=expln_ytd_#{@exp_id}_#{@incr} name=textfield42[#{@number}] class=variance_inputfield expand40-300 style=width:179px;overflow:hidden;padding-top:0px; padding-bottom:0px;border-color:rgb(238,238,238); onblur=call_to_store_expln_cap(#{@exp_id},#{@month},#{@doc_id},#{@condition},\"#{escape_javascript(@type)}\",#{@incr},\"#{escape_javascript(@path)}\",this.value); jQuery(this).css(borderColor, #EEEEEE);></textarea></div><div class=tablecoll5 style=width:70px;><input id=cost_ytd_#{@exp_id}_#{@incr} type=text name=costfield[#{@number}] class=variance_inputfield disabled=true style=height:60px;padding-top:0px;padding-bottom:0px;border-color:rgb(238,238,238);width:65px;text-align:right!important; onblur=call_to_store_cost(#{@exp_id},#{@month},#{@doc_id},#{@condition},\"#{escape_javascript(@type)}\",#{@incr},this.value,#{@id},\"#{escape_javascript(@path)}\");jQuery(this).css(borderColor, #EEEEEE);></div><span style=margin:6px 0 0;padding:0 3px;position:absolute;right:0px; class=closeme onclick=delete_more_expln(#{@form_number},#{@exp_id});>X</span><div class=clear></div></div>')";
      else
        page << "jQuery('#{table_name}').html('<div class=add-explanation><div class=tablecoll5 style=margin-left:413px;width:181px;overflow:hidden;line-height:16px;><textarea id=expln_#{@exp_id}_#{@incr} name=textfield42[#{@number}] class=variance_inputfield expand40-300 style=width:179px;overflow:hidden;padding-top:0px; padding-bottom:0px;border-color:rgb(238,238,238); onblur=call_to_store_expln_cap(#{@exp_id},#{@month},#{@doc_id},#{@condition},\"#{escape_javascript(@type)}\",#{@incr},\"#{escape_javascript(@path)}\",this.value); jQuery(this).css(borderColor, #EEEEEE);></textarea></div><div class=tablecoll5 style=width:70px;><input id=cost_#{@exp_id}_#{@incr} type=text name=costfield[#{@number}] class=variance_inputfield disabled=true style=height:60px;padding-top:0px;padding-bottom:0px;border-color:rgb(238,238,238);width:65px;text-align:right!important; onblur=call_to_store_cost(#{@exp_id},#{@month},#{@doc_id},#{@condition},\"#{escape_javascript(@type)}\",#{@incr},this.value,#{@id},\"#{escape_javascript(@path)}\");jQuery(this).css(borderColor, #EEEEEE);></div><span style=margin:6px 0 0;padding:0 3px;position:absolute;right:0px; class=closeme onclick=delete_more_expln(#{@form_number},#{@exp_id});>X</span><div class=clear></div></div>')";
      end

    elsif @partial == "cap_exp" && @type == "build_imp"
      @msg = "capitial_build_imp"
      page << "jQuery('#{table_name}').html('<div class=add-explanation><div class=add_expln ><textarea  class=variance_inputfield expand40-300 style=width:178px;overflow:hidden;padding-top:0px;padding-bottom:0px;border-color:rgb(238, 238, 238); id=capitial_build_imp_box name=capitial_build_imp_box   onblur=text_msg_display(\"#{escape_javascript(@msg)}\");save_build_imp_exp(this.value,#{@exp_id},#{@month},#{@condition},#{@doc_id},\"#{escape_javascript(@path)}\",\"#{escape_javascript(@type_val)}\");></textarea></div><div class=tablecol5 style=color:rgb(102,102,102);text-align:right;width:80px;margin-top:6px; id=financexp1><input type=text style=text-align:right;width:76px; disabled=true id=financexp_#{@exp_id}_#{@incr} onblur=call_to_store_cost(#{@exp_id},#{@month},#{@doc_id},#{@condition},#{escape_javascript(@type_val)},#{@incr},this.value,#{@id},#{escape_javascript(@path)});></div><span style=margin:0px 0 0;padding:0 3px;position:absolute;right:0px; class=closeme onclick=delete_more_expln(#{@form_number},#{@exp_id});>X</span><div class=clear></div></div>')";

    elsif @partial == "cap_exp" && @type == "tenant_imp"
      @msg = "capitial_tenant_imp"
      page << "jQuery('#{table_name}').html('<div class=add-explanation><div class=add_expln ><textarea  class=variance_inputfield expand40-300 style=width:178px;overflow:hidden;padding-top:0px;padding-bottom:0px;border-color:rgb(238, 238, 238); id=capitial_tenant_imp_box name=capitial_tenant_imp_box onblur=text_msg_display(\"#{escape_javascript(@msg)}\");save_build_imp_exp(this.value,#{@exp_id},#{@month},#{@condition},#{@doc_id},\"#{escape_javascript(@path)}\",\"#{escape_javascript(@type_val)}\");></textarea></div><div class=tablecol5 style=color:rgb(102,102,102);text-align:right;width:80px;margin-top:6px; id=financexp1><input type=text style=text-align:right;width:76px; disabled=true id=financexp_#{@exp_id}_#{@incr} onblur=call_to_store_cost(#{@exp_id},#{@month},#{@doc_id},#{@condition},\"#{escape_javascript(@type_val)}\",#{@incr},this.value,#{@id},#{escape_javascript(@path)});></div><span style=margin:0px 0 0;padding:0 3px;position:absolute;right:0px; class=closeme onclick=delete_more_expln(#{@form_number},#{@exp_id});>X</span><div class=clear></div></div>')";

    elsif @partial == "cap_exp" && @type == "leasing_comm"
      @msg = "capitial_lease_comm"
      page << "jQuery('#{table_name}').html('<div class=add-explanation><div class=add_expln><textarea  class=variance_inputfield expand40-300 style=width:178px;overflow:hidden;padding-top:0px;padding-bottom:0px border-color:rgb(238, 238, 238); id=capitial_lease_comm_box name=capitial_lease_comm_box onblur=text_msg_display(\"#{escape_javascript(@msg)}\");save_build_imp_exp(this.value,#{@exp_id},#{@month},#{@condition},#{@doc_id},\"#{escape_javascript(@path)}\",\"#{escape_javascript(@type_val)}\");></textarea></div> <div class=tablecol5 style=color:rgb(102,102,102);text-align:right;width:80px;margin-top:6px; id=financexp1><input type=text style=text-align:right;width:76px; disabled=true id=financexp_#{@exp_id}_#{@incr} onblur=call_to_store_cost(#{@exp_id},#{@month},#{@doc_id},#{@condition},#{escape_javascript(@type_val)},#{@incr},this.value,#{@id},#{escape_javascript(@path)});></div><span style=margin:0px 0 0;padding:0 3px;position:absolute;right:0px; class=closeme onclick=delete_more_expln(#{@form_number},#{@exp_id});>X</span><div class=clear></div></div>')";

    elsif @partial == "cap_exp" && @type == "lease_cost"
      @msg = "capitial_lease_cost"
      page << "jQuery('#{table_name}').html('<div class=add-explanation><div class=add_expln><textarea  class=variance_inputfield expand40-300 style=width:178px;overflow:hidden;padding-top:0px;padding-bottom:0px border-color:rgb(238, 238, 238); id=capitial_lease_cost_box name=capitial_lease_cost_box onblur=text_msg_display(\"#{escape_javascript(@msg)}\");save_build_imp_exp(this.value,#{@exp_id},#{@month},#{@condition},#{@doc_id},\"#{escape_javascript(@path)}\",\"#{escape_javascript(@type_val)}\");></textarea></div> <div class=tablecol5 style=color:rgb(102,102,102);text-align:right;width:80px;margin-top:6px; id=financexp1><input type=text style=text-align:right;width:76px; disabled=true id=financexp_#{@exp_id}_#{@incr} onblur=call_to_store_cost(#{@exp_id},#{@month},#{@doc_id},#{@condition},#{escape_javascript(@type_val)},#{@incr},this.value,#{@id},#{escape_javascript(@path)});></div><span style=margin:0px 0 0;padding:0 3px;position:absolute;right:0px; class=closeme onclick=delete_more_expln(#{@form_number},#{@exp_id});>X</span><div class=clear></div></div>')";

    elsif @partial == "cap_exp" && @type == "total_cap_ex"
      @msg = "total_cap_ex_cost"
      page << "jQuery('#{table_name}').html('<div class=add-explanation><div class=add_expln><textarea  class=variance_inputfield expand40-300 style=width:178px;overflow:hidden;padding-top:0px;padding-bottom:0px border-color:rgb(238, 238, 238); id=total_cap_ex_cost_box name=total_cap_ex_cost_box onblur=text_msg_display(\"#{escape_javascript(@msg)}\");save_build_imp_exp(this.value,#{@exp_id},#{@month},#{@condition},#{@doc_id},\"#{escape_javascript(@path)}\",\"#{escape_javascript(@type_val)}\");></textarea></div> <div class=tablecol5 style=color:rgb(102,102,102);text-align:right;width:80px;margin-top:6px; id=financexp1><input type=text style=text-align:right;width:76px; disabled=true id=financexp_#{@exp_id}_#{@incr} onblur=call_to_store_cost(#{@exp_id},#{@month},#{@doc_id},#{@condition},#{escape_javascript(@type_val)},#{@incr},this.value,#{@id},#{escape_javascript(@path)});></div><span style=margin:0px 0 0;padding:0 3px;position:absolute;right:0px; class=closeme onclick=delete_more_expln(#{@form_number},#{@exp_id});>X</span><div class=clear></div></div>')";

    elsif @partial == "cap_exp" && @type == "net_lease"
      @msg = "capitial_net_lease"
      page << "jQuery('#{table_name}').html('<div class=add-explanation><div class=add_expln><textarea  class=variance_inputfield expand40-300 style=width:178px;overflow:hidden;padding-top:0px;padding-bottom:0px border-color:rgb(238, 238, 238); id=capitial_net_lease_box name=capitial_net_lease_box onblur=text_msg_display(\"#{escape_javascript(@msg)}\");save_build_imp_exp(this.value,#{@exp_id},#{@month},#{@condition},#{@doc_id},\"#{escape_javascript(@path)}\",\"#{escape_javascript(@type_val)}\");></textarea></div> <div class=tablecol5 style=color:rgb(102,102,102);text-align:right;width:80px;margin-top:6px; id=financexp1><input type=text style=text-align:right;width:76px; disabled=true id=financexp_#{@exp_id}_#{@incr} onblur=call_to_store_cost(#{@exp_id},#{@month},#{@doc_id},#{@condition},#{escape_javascript(@type_val)},#{@incr},this.value,#{@id},#{escape_javascript(@path)});></div><span style=margin:0px 0 0;padding:0 3px;position:absolute;right:0px; class=closeme onclick=delete_more_expln(#{@form_number},#{@exp_id});>X</span><div class=clear></div></div>')";

    elsif @partial == "cap_exp" && @type == "loan_cost"
      @msg = "capitial_loan_cost"
      page << "jQuery('#{table_name}').html('<div class=add-explanation><div class=add_expln><textarea  class=variance_inputfield expand40-300 style=width:178px;overflow:hidden;padding-top:0px;padding-bottom:0px border-color:rgb(238, 238, 238); id=capitial_loan_cost_box name=capitial_loan_cost_box onblur=text_msg_display(\"#{escape_javascript(@msg)}\");save_build_imp_exp(this.value,#{@exp_id},#{@month},#{@condition},#{@doc_id},\"#{escape_javascript(@path)}\",\"#{escape_javascript(@type_val)}\");></textarea></div> <div class=tablecol5 style=color:rgb(102,102,102);text-align:right;width:80px;margin-top:6px; id=financexp1><input type=text style=text-align:right;width:76px; disabled=true id=financexp_#{@exp_id}_#{@incr} onblur=call_to_store_cost(#{@exp_id},#{@month},#{@doc_id},#{@condition},#{escape_javascript(@type_val)},#{@incr},this.value,#{@id},#{escape_javascript(@path)});></div><span style=margin:0px 0 0;padding:0 3px;position:absolute;right:0px; class=closeme onclick=delete_more_expln(#{@form_number},#{@exp_id});>X</span><div class=clear></div></div>')";
    end
  end
end